[package]
name = "bitstr"
version = "0.1.0"
edition = "2021"


[dependencies]
proptest = { version = "=1.5.0", optional = true }
rand = { version = "*", optional = true }

[features]
proptest = ["dep:proptest", "dep:rand"]

[dev-dependencies]
proptest = "=1.5.0"
rand = "*"
