CREATE MACRO empty_space(b, w) AS ~b & ~w;
CREATE MACRO moves_bu1(b, w) AS (((b >> 11) & w) >> 11) & empty_space(b, w);
CREATE MACRO moves_bu2(b, w) AS ((((((b >> 11) & w) >> 11) & empty_space(b, w) >> 11) & w) >> 11) & empty_space(b, w);
CREATE MACRO moves_bu3(b, w) AS (((((((((b >> 11) & w) >> 11) & empty_space(b, w) >> 11) & w) >> 11) & empty_space(b, w) >> 11) & w) >> 11) & empty_space(b, w);
CREATE MACRO moves_bu4(b, w) AS ((((((((((((b >> 11) & w) >> 11) & empty_space(b, w) >> 11) & w) >> 11) & empty_space(b, w) >> 11) & w) >> 11) & empty_space(b, w) >> 11) & w) >> 11) & empty_space(b, w);
CREATE MACRO moves_bu5(b, w) AS (((((((((((((((b >> 11) & w) >> 11) & empty_space(b, w) >> 11) & w) >> 11) & empty_space(b, w) >> 11) & w) >> 11) & empty_space(b, w) >> 11) & w) >> 11) & empty_space(b, w) >> 11) & w) >> 11) & empty_space(b, w);
CREATE MACRO moves_bd1(b, w) AS (((b << 11) & w) << 11) & empty_space(b, w);
CREATE MACRO moves_bd2(b, w) AS ((((((b << 11) & w) << 11) & empty_space(b, w) << 11) & w) << 11) & empty_space(b, w);
CREATE MACRO moves_bd3(b, w) AS (((((((((b << 11) & w) << 11) & empty_space(b, w) << 11) & w) << 11) & empty_space(b, w) << 11) & w) << 11) & empty_space(b, w);
CREATE MACRO moves_bd4(b, w) AS ((((((((((((b << 11) & w) << 11) & empty_space(b, w) << 11) & w) << 11) & empty_space(b, w) << 11) & w) << 11) & empty_space(b, w) << 11) & w) << 11) & empty_space(b, w);
CREATE MACRO moves_bd5(b, w) AS (((((((((((((((b << 11) & w) << 11) & empty_space(b, w) << 11) & w) << 11) & empty_space(b, w) << 11) & w) << 11) & empty_space(b, w) << 11) & w) << 11) & empty_space(b, w) << 11) & w) << 11) & empty_space(b, w);
CREATE MACRO moves_bl1(b, w) AS (((b >> 1) & w) >> 1) & empty_space(b, w);
CREATE MACRO moves_bl2(b, w) AS ((((((b >> 1) & w) >> 1) & empty_space(b, w) >> 1) & w) >> 1) & empty_space(b, w);
CREATE MACRO moves_bl3(b, w) AS (((((((((b >> 1) & w) >> 1) & empty_space(b, w) >> 1) & w) >> 1) & empty_space(b, w) >> 1) & w) >> 1) & empty_space(b, w);
CREATE MACRO moves_bl4(b, w) AS ((((((((((((b >> 1) & w) >> 1) & empty_space(b, w) >> 1) & w) >> 1) & empty_space(b, w) >> 1) & w) >> 1) & empty_space(b, w) >> 1) & w) >> 1) & empty_space(b, w);
CREATE MACRO moves_bl5(b, w) AS (((((((((((((((b >> 1) & w) >> 1) & empty_space(b, w) >> 1) & w) >> 1) & empty_space(b, w) >> 1) & w) >> 1) & empty_space(b, w) >> 1) & w) >> 1) & empty_space(b, w) >> 1) & w) >> 1) & empty_space(b, w);
CREATE MACRO moves_br1(b, w) AS (((b << 1) & w) << 1) & empty_space(b, w);
CREATE MACRO moves_br2(b, w) AS ((((((b << 1) & w) << 1) & empty_space(b, w) << 1) & w) << 1) & empty_space(b, w);
CREATE MACRO moves_br3(b, w) AS (((((((((b << 1) & w) << 1) & empty_space(b, w) << 1) & w) << 1) & empty_space(b, w) << 1) & w) << 1) & empty_space(b, w);
CREATE MACRO moves_br4(b, w) AS ((((((((((((b << 1) & w) << 1) & empty_space(b, w) << 1) & w) << 1) & empty_space(b, w) << 1) & w) << 1) & empty_space(b, w) << 1) & w) << 1) & empty_space(b, w);
CREATE MACRO moves_br5(b, w) AS (((((((((((((((b << 1) & w) << 1) & empty_space(b, w) << 1) & w) << 1) & empty_space(b, w) << 1) & w) << 1) & empty_space(b, w) << 1) & w) << 1) & empty_space(b, w) << 1) & w) << 1) & empty_space(b, w);
CREATE MACRO moves_wu1(b, w) AS (((w >> 11) & b) >> 11) & empty_space(b, w);
CREATE MACRO moves_wu2(b, w) AS ((((((w >> 11) & b) >> 11) & empty_space(b, w) >> 11) & b) >> 11) & empty_space(b, w);
CREATE MACRO moves_wu3(b, w) AS (((((((((w >> 11) & b) >> 11) & empty_space(b, w) >> 11) & b) >> 11) & empty_space(b, w) >> 11) & b) >> 11) & empty_space(b, w);
CREATE MACRO moves_wu4(b, w) AS ((((((((((((w >> 11) & b) >> 11) & empty_space(b, w) >> 11) & b) >> 11) & empty_space(b, w) >> 11) & b) >> 11) & empty_space(b, w) >> 11) & b) >> 11) & empty_space(b, w);
CREATE MACRO moves_wu5(b, w) AS (((((((((((((((w >> 11) & b) >> 11) & empty_space(b, w) >> 11) & b) >> 11) & empty_space(b, w) >> 11) & b) >> 11) & empty_space(b, w) >> 11) & b) >> 11) & empty_space(b, w) >> 11) & b) >> 11) & empty_space(b, w);
CREATE MACRO moves_wd1(b, w) AS (((w << 11) & b) << 11) & empty_space(b, w);
CREATE MACRO moves_wd2(b, w) AS ((((((w << 11) & b) << 11) & empty_space(b, w) << 11) & b) << 11) & empty_space(b, w);
CREATE MACRO moves_wd3(b, w) AS (((((((((w << 11) & b) << 11) & empty_space(b, w) << 11) & b) << 11) & empty_space(b, w) << 11) & b) << 11) & empty_space(b, w);
CREATE MACRO moves_wd4(b, w) AS ((((((((((((w << 11) & b) << 11) & empty_space(b, w) << 11) & b) << 11) & empty_space(b, w) << 11) & b) << 11) & empty_space(b, w) << 11) & b) << 11) & empty_space(b, w);
CREATE MACRO moves_wd5(b, w) AS (((((((((((((((w << 11) & b) << 11) & empty_space(b, w) << 11) & b) << 11) & empty_space(b, w) << 11) & b) << 11) & empty_space(b, w) << 11) & b) << 11) & empty_space(b, w) << 11) & b) << 11) & empty_space(b, w);
CREATE MACRO moves_wl1(b, w) AS (((w >> 1) & b) >> 1) & empty_space(b, w);
CREATE MACRO moves_wl2(b, w) AS ((((((w >> 1) & b) >> 1) & empty_space(b, w) >> 1) & b) >> 1) & empty_space(b, w);
CREATE MACRO moves_wl3(b, w) AS (((((((((w >> 1) & b) >> 1) & empty_space(b, w) >> 1) & b) >> 1) & empty_space(b, w) >> 1) & b) >> 1) & empty_space(b, w);
CREATE MACRO moves_wl4(b, w) AS ((((((((((((w >> 1) & b) >> 1) & empty_space(b, w) >> 1) & b) >> 1) & empty_space(b, w) >> 1) & b) >> 1) & empty_space(b, w) >> 1) & b) >> 1) & empty_space(b, w);
CREATE MACRO moves_wl5(b, w) AS (((((((((((((((w >> 1) & b) >> 1) & empty_space(b, w) >> 1) & b) >> 1) & empty_space(b, w) >> 1) & b) >> 1) & empty_space(b, w) >> 1) & b) >> 1) & empty_space(b, w) >> 1) & b) >> 1) & empty_space(b, w);
CREATE MACRO moves_wr1(b, w) AS (((w << 1) & b) << 1) & empty_space(b, w);
CREATE MACRO moves_wr2(b, w) AS ((((((w << 1) & b) << 1) & empty_space(b, w) << 1) & b) << 1) & empty_space(b, w);
CREATE MACRO moves_wr3(b, w) AS (((((((((w << 1) & b) << 1) & empty_space(b, w) << 1) & b) << 1) & empty_space(b, w) << 1) & b) << 1) & empty_space(b, w);
CREATE MACRO moves_wr4(b, w) AS ((((((((((((w << 1) & b) << 1) & empty_space(b, w) << 1) & b) << 1) & empty_space(b, w) << 1) & b) << 1) & empty_space(b, w) << 1) & b) << 1) & empty_space(b, w);
CREATE MACRO moves_wr5(b, w) AS (((((((((((((((w << 1) & b) << 1) & empty_space(b, w) << 1) & b) << 1) & empty_space(b, w) << 1) & b) << 1) & empty_space(b, w) << 1) & b) << 1) & empty_space(b, w) << 1) & b) << 1) & empty_space(b, w);
