[package]
name = "bitarray"
version = "0.1.0"
edition = "2021"


[dependencies]
proptest = { version = "=1.5.0", optional = true }

[features]
proptest = ["dep:proptest"]

[dev-dependencies]
proptest = "=1.5.0"
