[package]
name = "konane"
version = "0.1.0"
edition = "2021"

[dependencies]
bitarray = { path = "../bitarray" }
cgt = { version = "0.5", optional = true }
sled = "*"
thiserror = "*"

[features]
cgt = ["dep:cgt"]
rayon = ["cgt/rayon"]

[[bin]]
name = "konane2canonical"
required-features = ["cgt"]

[dev-dependencies]
criterion = "=0.5.1"

[[bench]]
name = "canonical"
harness = false
required-features = ["cgt"]
