[package]
name = "konane"
version = "0.1.0"
edition = "2021"

[dependencies]
bitarray = { path = "../bitarray" }
cgt = { version = "0.5", optional = true }

[features]
cgt = ["dep:cgt"]
rayon = ["cgt/rayon"]

[[bin]]
name = "konane2canonical"
required-features = ["cgt"]

