ub/workflows/copy-openapi-file.yml

name: Copy updated OpenAPI file

# only run this workflow when the openapi file has changed on the master branch
on: 
  push:
    branches: 
      - main
    paths:
      - 'notehub/api/openapi.yaml'
  workflow_dispatch:

jobs:
  copy_web_to_gh_pages: 
    runs-on: ubuntu-latest
    steps:
    - name: Check out GitHub konjecture repo
      uses: actions/checkout@v3
    - name: Check out GitHub Pages repo
      uses: actions/checkout@v3
      with:
        repository: ishehadeh/ishehadeh.github.io
        path: ./ishehadeh.github.io
    - name: Copy walkthrough.html to www/konane.html
      run: cp ./web/walkthrough.html ./ishehadeh.github.io/www/konane.html
    - name: Commit update in GitHub pages repo
      run: bash ./.github/scripts/push-openapi-to-notehub-js.sh
      env:
        BRANCH: master