name: Deploy web/walkthrough.html

# only run this workflow when the openapi file has changed on the master branch
on: 
  push:
    branches: 
      - main
    paths:
      - 'web/walkthrough.html'
  workflow_dispatch:


jobs:
  copy_web_to_gh_pages: 
    permissions:
      id-token: write
      contents: write
      pages: write
    runs-on: ubuntu-latest
    steps:
    - name: Check out GitHub konjecture repo
      uses: actions/checkout@v3
    - name: Check out GitHub Pages repo
      uses: actions/checkout@v3
      with:
        repository: ishehadeh/ishehadeh.github.io
        path: ./ishehadeh.github.io
        ref: 'master'
        token:  ${{ secrets.PAGES_REPO_PAT }}
    - name: Copy walkthrough.html to www/konane.html
      run: cp web/walkthrough.html ./ishehadeh.github.io/www/konane.html
    
    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Commit update in GitHub pages repo
      run: |
        cd ./ishehadeh.github.io
        git add www/konane.html
        git commit -m 'update konane'
    
    - name: Git Push
      run: |
        cd ./ishehadeh.github.io
        git push origin master